version: 0.0
os: linux
files:
  - source: /opt/deploy/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
  AfterInstall:
    - location: scripts/restart_server
      timeout: 300
      
